import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/shared/styles/globals.css'
import { Providers } from '@/app/(client)/shared/providers'
import { ThemeSwitcher } from '@/app/(client)/widgets/theme-switcher'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className='fixed top-4 right-4 z-50'>
            <ThemeSwitcher />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
