// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "not_found_title": "Not Found",
  "not_found_description": "The page you are looking for does not exist.",
  "not_found_button": "Go Back",
  "not_found_subcategories_description": "Characters not found.",
  "back_to_top": "Back to top",
  "more_info": "More info",
  "less_info": "Less info",
  "show_more": "Show more",
  "show_less": "Show less"
};
export default messages;